### ISSUE TITLE
Drop the develop branch

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk-cli#19]
We did the same in the gateway and all other repos. We should only have one main branch - `master`.

This is slightly tricky as it needs fixing in other places like the gateway release scripts, which at the moment build master. They should be switched to building specific `tyk-cli` tags (or commit SHAs, if we don't want to do releases yet).

/cc @buger @lonelycode @kohrVid

**Comment by buger** [comment]
👍
