### ISSUE TITLE
As a user I should be able to validate an API Definition using the CLI

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk-cli#2]
We can validate an API definition:

     tyk-cli api {id} test

Proposed output:

    Validation: Error
    [middleware1]
    Required {option n}
    [middleware2]
    Required {option 1}

From: "tyk-97: Tyk-Cli v0.2"

**Comment by kohrVid** [comment]
Regarding this issue, I don't think it's possible to write Cobra commands in the suggested format (i.e., `appName command [argument] subCommand` ). I will try to look into this a little further but if this isn't possible, I'm assuming that using the following format as an alternative would be ok:

    appName command subCommand argument
or,

    tyk-cli api test {id}

Saying that, as the import and export features  (#3) were written to potentially contain functions that could import policies, tokens &c. as well as APIs, should this command perhaps be a more generic `test` with the test type (in this case "api") and  required ID given as an argument/subcommand?

e.g.,

    tyk-cli test api --id={id}

**Comment by lonelycode** [comment]
Just because a lib doesn't support the design doesn't mean we should change the design. A lot of time and thought went into the command structure as it was proposed.

So you'll need to go back to the design doc and come up with a counter-proposal for all the cases instead of changing it on the fly.

**Comment by kohrVid** [comment]
I really was just trying to find out which direction to take should the library not cater to the desired format (or hopefully find out if anyone else knew how to create the desired command structure using the Cobra package).

Where exactly is the design document for the CLI project? I've been responding to issues raised either here or on Jixee up until now.

**Comment by lonelycode** [comment]
I've shared the doc with you, it;'s not public atm.

**Comment by buger** [comment]
@lonelycode can you share with me as well?

**Comment by mvdan** [comment]
@buger do you still want access to the doc?

**Comment by mvdan** [comment]
> Just because a lib doesn't support the design doesn't mean we should change the design.

Jess filled me in and we investigated into Cobra. As it turns out, the library is quite powerful but doesn't do a lot of arg handling itself. Sub-commands can only be the first argument of their parent, so `tyk-cli api <id> subcmd` isn't trivial. Its hierarchical command structure can only `tyk-cli api subcmd <id>`.

We managed to get it to work by implementing `subcmd` directly in the `api` command though, which seems to work OK:

```
 $ ./f api
Error: need to specify api id
Usage:
  app api [id] [flags]
 $ ./f api 3
selected api 3
 $ ./f api 3 test
test 3 with args: []
 $ ./f api 3 test foo bar
test 3 with args: [foo bar]
```

**Comment by buger** [comment]
@mvdan already have it.

**Comment by matiasinsaurralde** [comment]
@lonelycode We were discussing about this with @kohrVid yesterday, I assume the ID we'll be using as the input here, it's a temporary/internal ID, a definition that was not yet "pushed", right?

**Comment by lonelycode** [comment]
Yeah it will need to be, if it's a pushed api then we use the real api ID, if it's staged, it should be something temporary - not sure how viable that is...

**Comment by mvdan** [comment]
Done in #16.
