### ISSUE TITLE
Add flag for local manifest file name to read from

### ISSUE THREAD

**Issue by bitsofinfo** [TykTechnologies/tyk-cli#24]
I have a directory of a ton of JS plugins that can interoperate w/ one another, and different combinations of manifest files, named like "manifest-scenario1.json" and "manifest-scenario2.json"

Would be great to be able to:

```
tyk-cli bundle build --manifest-source-file ./manifest-scenario1.json --output scenario1-bundle.zip
```

Which would result in a ZIP where the "manifest.json" has the contents of `manifest-scenario1.json`

**Comment by matiasinsaurralde** [comment]
Would it merge the JSON structures? Can you provide sample input/output?

**Comment by bitsofinfo** [comment]
no merging, just take the contents of manifest-scenario1.json and write it into the zip as manifest.json

**Comment by bitsofinfo** [comment]
Can this be done?

**Comment by bitsofinfo** [comment]
@matiasinsaurralde ?

**Comment by bitsofinfo** [comment]
?

**Comment by matiasinsaurralde** [comment]
Hi @bitsofinfo, we're currently planning [this](https://github.com/TykTechnologies/tyk/issues/1492) so further changes might take place in the gateway repository, we will keep you updated.

**Comment by l3ender** [comment]
Does using `tyk` binary to bundle (create a manifest) support using a different filename to accomplish the ask in this ticket?

**Comment by buger** [comment]
@l3ender actually yes, and this code was moved to tyk project https://github.com/TykTechnologies/tyk/blob/master/cli/bundler/bundler.go#L218

So command will be: `tyk bundle --manifest ./manifest-scenario1.json --output scenario1-bundle.zip`

Also closing this ticket and will archivate this project with proper notice. 

Cheers1
