### ISSUE TITLE
User/environment configuration

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk-cli#9]
Users should be able to configure user credentials either in BoltDB or in JSON format. This configuration will work in a similar manner to Git `remotes` but will instead require:

* a URL
* a token
* an alias

It would then be possible for users to select an environment and switch from one to another.

**Comment by kohrVid** [comment]
It is unclear as to which fields and what information will need to be stored in said files. For example, the config files may contain a list of Dashboards or Gateways.

**Comment by mvdan** [comment]
If the amount of information is small, just go for JSON. BoltDB won't be plaintext and is overkill unless we're storing lots of things or storing very often.

I'd think of it as part of the `tyk-cli` config. You could even have this under a `remotes` key, since many people are already familiar with Git terms.

**Comment by matiasinsaurralde** [comment]
I like JSON for these settings.

About using `remote` 👍

**Comment by kohrVid** [comment]
@mvdan & @matias, where do you think the configuration files should be saved? I'd initially thought that it would make sense to put these in the `/etc/` folder for *Nix users but it then occurred to me that Windows users often have config files saved in their home folders (e.g., `C:\Users\<Username>\AppData\Roaming\TykCLI`). Should I place config files in the home folder instead (perhaps in a hidden subdirectory)?

**Comment by mvdan** [comment]
For now I'd keep things simple and just use a file in the current directory. This is what the gateway and dashboard do.

This would also allow having multiple directories, one per Tyk install - and keeping all the settings and data separate.

Later, if you want, you can add well-known paths as fallback options including `/etc/foo/`, `~/.config/foo/` and their windows/mac counterparts. But I don't think that's strictly necessary.

**Comment by kohrVid** [comment]
Doesn't the Gateway just copy its config file into `/etc/` during the installation process?

**Comment by mvdan** [comment]
Yeah, both the gateway and dashboard use `/etc/foo.conf` as a fallback if `foo.conf` doesn't exist. That's what I meant in the last paragraph. But I wouldn't worry about system paths for now.
